name: Test
on:
  push:864945151293653084
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./bin/detect
    - run: ./bin/compile $PWD
    - run: ./bin/release
